Desktop Version
Shakir-Hussain12/Mobile-Portfolio pull request #7
Opened 2022-12-08 11:12 UTC by Shakir-Hussain12

### Added the following things
---
- New Images fit to desktop size
- New classes to existing elements for desired styling
- Styled all elements to fit the desktop screen

2022-12-08 12:00 UTC, OyePriscilla requested changes
Hi @Shakir-Hussain12  😃, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)

## Highlights
Github flow observed✔️
Linters checks passed ✔️ 

## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 12:00 UTC, OyePriscilla commented on Style.css
> +  }
- [ ] You may want to remove the gap property and align the children component as we have it in the figma design. 👍 
- [ ] The technology languages need little adjustment, kindly adjust the width. 👍 

## Figma Design

![socialmedia](https://user-images.githubusercontent.com/103386183/206436763-eecb7ef7-132b-4f6c-ab56-fee8e57538db.png)

2022-12-08 12:00 UTC, OyePriscilla commented on Style.css
> +  }
- [ ] Please 🙏  I noticed also that you will perhaps need to position the carets (right and down arrow) properly according to the template for the mobile version. 👍

2022-12-08 12:00 UTC, OyePriscilla commented on Style.css
> +  }
- [ ] Please kindly re-check, I noticed that all your cards are not responsive as expected; @ min-width: 768px this is what I have 👇 (The same thing apply to `.headline` and `.contact-me` sections as well).

## 
![socialmedia](https://user-images.githubusercontent.com/103386183/206439491-54c775f9-c271-444d-a76f-bf9b2b9f11e3.png)

## 
![socialmedia](https://user-images.githubusercontent.com/103386183/206441136-100cc2a7-24f3-4821-ad06-cd06f004b4fe.png)

2022-12-09 08:01 UTC, jerryowusu requested changes
Hi @Shakir-Hussain12  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost there](https://user-images.githubusercontent.com/65233860/206653751-3e55a85a-da01-4d50-9935-55ba2b20061c.jpg)


 ## Highlights
All linters are passing :+1: 
Neat and well organised code :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 08:01 UTC, jerryowusu commented on Style.css
> +    background-size: cover;
As requested by the previous reviewer, the headline card is still not responsive because only part of the background image appears till you increase the with to a certain point. :disappointed:  Kindly consider changing the `background-size: cover` to `background-size: contain` to make the image appear fully and responsive :wink: 
Your design

![Screenshot from 2022-12-09 07-34-35](https://user-images.githubusercontent.com/65233860/206652284-42051846-2158-4b7d-a32e-0536540328b6.png)

The figma design


![Screenshot from 2022-12-09 07-34-04](https://user-images.githubusercontent.com/65233860/206652362-ec083983-d95c-44e1-a268-c03a602e125b.png)

2022-12-09 08:01 UTC, jerryowusu commented on Style.css
> +  }
- [x] [OPTIONAL] Kindly consider adding margin around the individual cards to make it to conform to the design.  :wink: 

Your design

![Screenshot from 2022-12-09 07-54-28](https://user-images.githubusercontent.com/65233860/206653164-2d48e8e7-442c-4073-809e-48fd5f66b4b3.png)


The figma design

![Screenshot from 2022-12-09 07-54-43](https://user-images.githubusercontent.com/65233860/206653209-6fef5f5e-ac27-4f53-b8ef-dc9cf6960575.png)

2022-12-09 10:59 UTC, christianbiring1 approved these changes
Hi @Shakir-Hussain12 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![imageswelljob](https://user-images.githubusercontent.com/97100091/206687339-5fbf60e2-413e-4147-bbcd-da878c622d57.jpeg)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
- [ ] Good commit messages :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 11:00 UTC, merged